services:
  web:
    build: .
    container_name: pnn
    ports:
      - "5000:5000"
    expose:
      - "5000"
    networks:
      - siscalc 
    volumes:
      - .:/app
      - static_volume:/var/www/static
    working_dir: /app      
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - siscalc
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/var/www/static:ro
    depends_on:
      - web
volumes:
  static_volume:
networks:  
  siscalc:
    external: true
