services:
  pnn:
    build: .
    container_name: pnn
    ports:
      - "8008:8008"
    networks:
      - siscalc 
    volumes:
      - .:/app
    working_dir: /app      
    environment:
      - FLASK_ENV=development
    restart: unless-stopped
networks:  
  siscalc:
    external: true